.\" Manpage for acme cron.
.\" Contact acme@rapsys.eu to correct errors or typos.
.TH man 1 "19 Apr 2020" "2\&.0\&.0" "acme-cron man page"
.SH "NAME"
acme-cron \- the acme cron job

.SH "SYNOPSIS"
\fIacme\fR cron [\-(v|\-verbose)] [\-(c|\-config)[=/etc/acme/config]] [example.com] [...]

.SH "DESCRIPTION"
Acme cert is a fast and simple certificate regenerator cron job.

.sp
See \fBacme-conf\fR(1) to configure your certificate and loot at \fBacme-cert\fR(1) to generate your certificate\&.

.SH "DOCUMENTATION"
A formated and hyperlinked copy of the lastest ACME v2 API documentation can be viewed at \fBhttps://ietf-wg-acme\&.github\&.io/acme/draft-ietf-acme-acme\&.html\fR\&.

.sp
This Acme implementation can be used for Let's Encrypt free, automated and open certificate authority, their documentation can be viewed at \fBhttps://letsencrypt\&.org/docs/\fR\&.

.SH "OPTIONS"
.PP
\-\-verbose
.RS 4
Produces a verbose report about the current process for the purpose of problem analysis\&.
.RE
.PP
\-\-config
.RS 4
Use the specified configuration file\&. If the pathname is omitted, the file specified in Acme::CONFIG constant (normally /etc/acme/config) is assumed\&.
.RE
.PP

.SH "ARGUMENTS"
.PP
\fBexample.com\fR
.RS 4
Will regenerate the certificate when older than 60 days for the domain as common name and the associated domains as subject alt names\&.
.RE
.PP
without argument
.RS 4
Will generate the certificate when older than 60 days for all domain and associated domains declared in the configuration file.
.RE

.SH "CRONJOBS"

.SS "CRON\&.DAILY SCRIPT"
You may add a daily cron by creating /etc/cron\&.daily/acme file with the content:
.nf
	#! /bin/sh
	acme cron
.fi

.sp
Don't forget to set the executable flag:
.nf
	# chmod a+x /etc/cron\&.daily/acme
.fi

.SS "CRONTAB FRAGMENT"
You may add a crontab fragment by creating /etc/cron\&.d/acme file with the content:
.nf
	#! /bin/sh
	0 0 * * *	\fBusername\fR	acme cron
.fi

.sp
Don't forget to replace \fBusername\fR with desired user identifier\&.

.SS "USER CRONTAB"
You may add a daily cron by running the following command :
.nf
	$ crontab -e
.fi

.sp
With the following content:
.nf
	#! /bin/sh
	0 0 * * *	acme cron
.fi

.SH "CONTRIBUTE"
You may buy me a Beer, a Tea or help with Server fees with a paypal donation to the address \m[blue]\fBpaypal@rapsys\&.eu\fR\m[] or via the donation page.

Don't forget to show your love for this project, feel free to report bugs to the author, issues which are security relevant should be disclosed privately first\&.

Patches are welcomed and grant credit when requested\&.

.SH "DONATION"
\m[blue]\fBhttps://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=JNWGK8Z2TBHFN\fR\m[]

.SH "FURTHER DOCUMENTATION"
A formated and hyperlinked copy of the lastest ACME v2 API documentation can be viewed at \fBhttps://ietf-wg-acme\&.github\&.io/acme/draft-ietf-acme-acme\&.html\fR\&.

.sp
This Acme implementation can be used for Let's Encrypt free, automated and open certificate authority, their documentation can be viewed at \fBhttps://letsencrypt\&.org/docs/\fR\&.

.SH "AUTHOR"
Raphaël Gertz (Rapsys) <acme@rapsys\&.eu>

.SH "BUGS"
No known bugs.

.SH "SEE ALSO"
\fBacme\fR(1), \fBacme-conf\fR(1), \fBacme-cert\fR(1)

.SH "ACME"
Part of the \fBacme\fR(1) suite
