.\" Manpage for acmeconf.
.\" Contact acme@rapsys.eu to correct errors or typos.
.TH man 1 "20 Jun 2017" "0.8" "acmeconf man page"
.SH NAME
acmeconf \- create a new configuration template
.SH SYNOPSIS
acmeconf [-(r|-redhat|d|-debian)] [example.com[,www.example.com,...]] [-(t|-term)[=https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf]] [...] > /etc/acme/config
.SH DESCRIPTION
acmeconf is a basic script generating a template configuration for generating letsencrypt certificate.
.SH OPTIONS
The acmeconf script takes multiple options.

Use -r or --redhat directive for a distribution using redhat certificate path (/etc/pki/tls).

Use -d or --debian for a distribution using debian like certificate base path (/etc/ssl).

These directives can be followed by domain and alternative(s) domain(s) list each separated by a coma, the first one of the list will be used as principal domain name.

Use -t or --term for letsencrypt license agreement.
.SH EXAMPLE 1
.TP
.B acmeconf -r example.com,www.example.com,ssl.example.com > /etc/acme/config
will generate redhat like template configuration file for example.com as principal domain and www.example.com with ssl.example.com as alternatives domains.
.SH EXAMPLE 2
.TP
.B acmeconf -r example.com,www.example.com -r webmail.example.com,imap.example.com,smtp.example.com | sudo tee /etc/acme/config
will generate redhat like template configuration file for example.com as principal domain and www.example.com with ssl.example.com as alternatives domains and an other one for the mail.example.com domain with example.com and smtp.example.com as alternatives domain.
.SH SEE ALSO
acmecron(1),acmecert(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Raphaël Gertz (rapsys) <acme@rapsys.eu>
